name: flet_onesignal
description: "Flutter OneSignal package integration for Python Flet."
version: 0.4.0
repository: https://github.com/brunobrown/flet-onesignal

environment:
  sdk: ^3.5.2
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  flet: ^0.80.5
  onesignal_flutter: ^5.4.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
